# Generated by Django 5.2.10 on 2026-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Не энергичная'), (2, 'Немного энергичная'), (3, 'Умеренно энергичная'), (4, 'Сильно энергичная'), (5, 'Очень сильно энергичная')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='home_type',
            field=models.CharField(choices=[('apartment', 'квартира'), ('house', 'дом')], max_length=9, verbose_name='Тип жилья'),
        ),
    ]
